Update app/views/templates/script/convert2rhel_analyze.erb
Co-authored-by: Adam Růžička <adamruzicka@users.noreply.github.com>

diff --git a/app/views/templates/script/convert2rhel_analyze.erb b/app/views/templates/script/convert2rhel_analyze.erb
--- a/app/views/templates/script/convert2rhel_analyze.erb
+++ b/app/views/templates/script/convert2rhel_analyze.erb
@@ -32,8 +32,8 @@ export CONVERT2RHEL_DISABLE_TELEMETRY=1
 /usr/bin/convert2rhel analyze -y
 
 errors=$(grep -c 'ERROR' '/var/log/convert2rhel/convert2rhel-pre-conversion.json')
-if [ "$errors" -gt 0 ]; then
-    echo "Error: $errors error(s) have been found."
+if ! grep -q ERROR /var/log/convert2rhel/convert2rhel-pre-conversion.json; then
+    echo "Error: Some error(s) have been found."
     echo "Exiting ..."
     exit 1
 fi
